# 인덱싱(indexing)

- ndarray에서 데이터를 검색하는 방법
- 인덱싱 방법
|종류|방법 | 특징|
|-----|-----|-----|
|단일값 인덱싱|arr[2]| 특정위치 단일값 출력|
|슬라이싱|arr[1:4]| 연속된 범위|
|팬시인덱싱|arr[[0, 2, 4]]|불연속 위치 다중값 출력|
|불린인덱싱|arr[arr > 5]| 조건에 맞는 값 출력|

### (1) 단일값 인덱싱

In [2]:
import numpy as np

In [3]:
#1~9까지 ndarray 데이터 생성
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 2번지의 데이터 출력
print(type(arr))
print(type(arr[2]))

print(arr.dtype)
print(arr[2].dtype)

print(arr.shape)
print(arr[2].shape)

<class 'numpy.ndarray'>
<class 'numpy.int64'>
int64
int64
(9,)
()


In [5]:
# 인덱스별 단일값 출력
print(arr)
print(arr[0])
print(arr[2])
print(arr[5])
print(arr[-1])
print(arr[-2])

[1 2 3 4 5 6 7 8 9]
1
3
6
9
8


### (2) 단일값 인덱싱을 통한 데이터 변경

In [6]:
arr[0] = 100
print(arr)
arr[-1] = 900
print(arr)

[100   2   3   4   5   6   7   8   9]
[100   2   3   4   5   6   7   8 900]


### (3) 2차원 배열
- 2차원 배열은 [행, 열] 기준으로 검색

In [7]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# 3행 3열의 2차원 배열로 변환
arr2 = np.reshape(arr, (3, 3))
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print(arr2.shape)
print(arr2[0, 2]) # 3 출력
print(arr2[2, 1]) # 8 출력
print(arr2[1, 1]) # 5 출력
print(arr2[-1, -1]) # 마지막 행, 마지막 열 출력

(3, 3)
3
8
5
9


#### (4) 슬라이싱
- ':' 기호를 이용하여 연속된 데이터를 출력

In [10]:
array1 = np.arange(1, 10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# 0, 1, 2 세 개의 데이터 출력
array1[0:3]

array([1, 2, 3])

In [12]:
print(array1[3:6]) #[4, 5, 6]
print(array1[0:3]) #[1, 2, 3]
print(array1[::2]) #[1, 3, 5, 7, 9]  
print(array1[::-1]) #[9, 8, 7... 1] 역순으로 출력
print(array1[-3: ]) #마지막 데이터 3개 출력

[4 5 6]
[1 2 3]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]
[7 8 9]


- 2차원 슬라이싱 : [행 범위, 컬럼 범위]

In [13]:
# 3행 3열의 2차원 배열 생성, 데이터 1~9
arr = np.arange(1, 10).reshape((3,3))  # reshape(object, shape...)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print(arr[0:1, 0:3])  # [[1 2 3]]
print(arr[0:2, 0:2])
print(arr[1:3, 1:3])
print(arr[:2, :3])
print(arr[2:, :3])

[[1 2 3]]
[[1 2]
 [4 5]]
[[5 6]
 [8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [15]:
print(arr[0], arr[0].shape) # 첫번째 로우 출력, 1차원 배열 
print(arr[2], arr[2].shape) # 마지막 로우 출력, 1차원 배열 

[1 2 3] (3,)
[7 8 9] (3,)


### (5) 팬시 인덱싱
- 불연속적인 여러 위치의 값을 인덱싱하여 출력

- 1차원 배열의 팬시 인덱싱

In [16]:
array1 = np.arange(1, 10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
print(array1[0])   # 단일값 인덱싱
print(array1[0:3]) # 슬라이싱
print(array1[[0, 2, 3]])  # 팬시 인덱싱

1
[1 2 3]
[1 3 4]


In [18]:
# 슬라이싱 + 팬시 인덱싱
value = array1[4:][[2, 4]]
print(value, value.shape)

[7 9] (2,)


- 2차원 배열 팬시 인덱싱

In [19]:
# (3, 3), 1~9
arr = np.arange(1,10).reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# [[행], [열]]
print(arr[[0, 1], 2]) 
print(arr[[0, 2], 2]) 
print(arr[[0, 2], 1]) 
print(arr[[0, 2], [1]]) 
print(arr[[0, 2], [0,2]]) # (0,0), (2,2)
print(arr[[0, 1, 2], 1]) # (0,1), (1,1), (2,1)

[3 6]
[3 9]
[2 8]
[2 8]
[1 9]
[2 5 8]


### (6) 불린 인덱싱
- 조건식을 사용하여 인덱싱
- 데이터 필터링에 자주 사용됨

In [21]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# 1차원 배열 arr의 데이터 중 5보다 큰 데이터만 출력
arr[arr > 5]

array([6, 7, 8, 9])

In [23]:
# 1차원 배열 arr의 데이터 중 5보다 작은 데이터만 출력
arr[arr < 5]

array([1, 2, 3, 4])

In [24]:
# 불린 인덱싱은 내부적으로 조건에 맞는 불린값으로 필터링을 실행 한 후 
# True 값만 출력
arr_bool = arr > 5
print(arr)
print(arr_bool, arr[arr_bool], arr[ arr> 5])

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True] [6 7 8 9] [6 7 8 9]


In [25]:
# arr 배열의 짝수, 홀수 값 출력
print(arr[arr % 2 == 0])
print(arr[arr % 2 == 1])

[2 4 6 8]
[1 3 5 7 9]


In [26]:
# 2의 배수 또는 5의 배수 출력, 단 |, & 연산 실행 시 조건을 괄호()로 묶어야 함
print(arr[(arr % 2 == 0) | (arr % 5 == 0)])

[2 4 5 6 8]


In [38]:
# for 루프 => [6, 7, 8, 9]
target = []
for i in range(1, len(arr)+1): #리스트 사용하니 range() 사용
    if i > 5:
        target.append(i)
print(target)
arr2 = np.array(target)
print(arr2)

[6, 7, 8, 9]
[6 7 8 9]


In [44]:
# 80점 이상 학생 이름 추출
names = np.array(['홍', '김', '최', '산', '강'])
scores = np.array([90, 87, 56, 94, 40])

# 80점 이상인 학생 출력
print(names[scores>80])

# 80점 이상인 점수 출력
print(scores[scores>80])

['홍' '김' '산']
[90 87 94]
