# 배열 연산
- 데이터셋의 쉐입(배열)이 같으면 연산이 가능)

In [76]:
import numpy as np

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [13]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])

In [14]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [18]:
arr1= np.array([[1, 2], [3, 4]])
arr2= np.array([[5, 6], [7, 8]])
print(arr1.shape)
print(arr2.shape) # 둘의 쉐입이 같아야 연산이 가능하다

(2, 2)
(2, 2)


In [19]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


# 정렬 - sort()와 argsort()

## (1) sort
- 원본유지 🅾️: numpy.sort()
- 원본유지 ❌: numpy.ndarray.sort()

In [26]:
org_arr = np.array([2,1,3,6,9])
org_arr

array([2, 1, 3, 6, 9])

In [27]:
# 오름차순 정렬 후 배열 반환
sort_arr = np.sort(org_arr)
print(sort_arr)
print(org_arr, sort_arr)

[1 2 3 6 9]
[2 1 3 6 9] [1 2 3 6 9]


In [31]:
arr = np.array([[5, 2], [10, 8]])

In [32]:
sort_arr = np.sort(arr, axis=0)
sort_arr #정렬이 안댐

array([[ 5,  2],
       [10,  8]])

In [34]:
sort_arr2 = np.sort(arr, axis=1)
sort_arr2 #작은 것에서 큰 것으로 정렬

array([[ 2,  5],
       [ 8, 10]])

# argsort()
- 배열을 정렬 후 반환

In [40]:
names = np.array(['홍', '김', '최', '산', '강'])
scores = np.array([90, 87, 56, 94, 40])

In [46]:
# 성젹순으로 names 배열을 오름차순 정렬 [::1]
print(names[scores.argsort()])
print(names[np.argsort(scores)])

['강' '최' '김' '홍' '산']
['강' '최' '김' '홍' '산']


In [47]:
# 성적순으로 names 배열을 내림차순으로 정렬
index = np.argsort(scores)[::-1]
print(names[index])

['산' '홍' '김' '최' '강']


# 집계 함수

In [53]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr)) # 표준편차
print(np.var(arr)) # 분산
print(np.median(arr)) # 중앙값

45
5.0
9
1
2.581988897471611
6.666666666666667
5.0


In [61]:
arr = np.array([[1,2,3], [4,5,6]])
print(np.sum(arr))
print(np.sum(arr, axis=1)) # 열방향 합계
print(np.sum(arr, axis=0)) # 행방향 합계

21
[ 6 15]
[5 7 9]


# 선형 대수 연산

## (1) 행렬 내적
- 행렬 내적의 곱셈은 **dot** 함수 사용
- 예) A(2,2) * B(3,2) = C(2,2)
- 규칙: A의 열 수 == B의 행 수가 동일할때만 내적 연산이 가능함
- np.transpose() 함수를 이용하여 행과 열을 바꿈

In [66]:
A = np.array([[1,2,3], 
             [4,5,6]])
B = np.array([[7, 8], 
             [9, 10], 
             [11,12]])

In [68]:
print(np.dot(A, B))

[[ 58  64]
 [139 154]]


In [71]:
A_T = np.transpose(A)
A_T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [74]:
A_T * B

array([[ 7, 32],
       [18, 50],
       [33, 72]])

# 기타 함수
- np.where(): 조건부 값 출력
- np.uniqe(): 중복 없는 고유한 값
- np.concatenate(): 배열을 결합

In [77]:
arr = np.arange(1, 10)

In [81]:
print(np.where(arr>5, 'big', 'small'))

['small' 'small' 'small' 'small' 'small' 'big' 'big' 'big' 'big']


In [87]:
# np.uniqe() 중복 없는 고유한 값을 반환
arr = np.array([1, 2, 2, 5, 3, 3, 2, 1, 6, 4, 5, 4, 7])

In [92]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [95]:
values, counts = np.unique(arr, return_counts=True)

In [96]:
print(values, counts)

[1 2 3 4 5 6 7] [2 3 2 2 2 1 1]


In [98]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= np.concatenate([a, b])
c

array([1, 2, 3, 4, 5, 6])